Repository henrikalbrecht/I05-Virtuelle-Maschinen, pull requests merged in 2024-01, with the labels that each got.

#64 Add dev Dockerfile
  src/docker/dockerfiles/dockerfile
Labels: documentation, education

#67 Add nvm and django dependencies to enable next.js react development and django development
  src/docker/dockerfiles/dockerfile
Labels: education

#68 Added Context and Container c4 diagram
  docs/architecture/c4-container.puml
  docs/architecture/c4-context.puml
Labels: documentation

#54 Uc3 glossar
  docs/requirements/glossary.adoc
  docs/requirements/images/uc01_wireframe_extension.png
  docs/requirements/images/uc03_wireframe.png
  docs/requirements/use_case_03.inc.adoc
Labels: documentation

#73 added __pycache__ folder to gitignore
  .gitignore
Labels: enhancement

#74 Add extension scenario for UC01
  docs/requirements/images/uc01_wireframe_extension.png
  docs/requirements/use_case_01.inc.adoc
Labels: enhancement

#77 Glossary
  docs/requirements/glossary.adoc
  docs/resources/Skizze von Wireframe Use Case Modell 01.vpp
  docs/resources/UC03 Wireframe.vpp
Labels: documentation

#80 Update README.md
  src/prototype/frontend/README.md
Labels: documentation, enhancement

#84 Frontend finally completed
  src/prototype/backend/app/serializers.py
  src/prototype/backend/db.sqlite3
  src/prototype/frontend/package-lock.json
  src/prototype/frontend/package.json
  src/prototype/frontend/src/app/components/Footer.tsx
  src/prototype/frontend/src/app/components/Header.tsx
  src/prototype/frontend/src/app/components/VmForm.tsx
  src/prototype/frontend/src/app/components/VmLists.tsx
  src/prototype/frontend/src/app/page.tsx
Labels: enhancement

#63 Risklist
  docs/project_management/resources/Risk_list_v1.csv
  docs/project_management/risk_list.adoc
Labels: documentation

#81 Risklist is complete
  docs/project_management/resources/Risklist.csv
  docs/project_management/risk_list.adoc
  docs/project_management/risks.csv
Labels: documentation

#89 fix risk list csv include
  docs/project_management/risk_list.adoc
Labels: documentation

#85 draft for final arch_nb
  docs/architecture/architecture_notebook.adoc
Labels: documentation

#87 added domain model
  docs/requirements/domain_model.adoc
  docs/requirements/images/domain_model.png
  docs/resources/domainmodel.vpp
Labels: documentation

#83 Überarbeitungen Glossar
  docs/requirements/glossary.adoc
Labels: documentation

#92 Dokusprint Use Case Model
  docs/requirements/use-case_model.adoc
Labels: documentation

#93 Dokusprint Systemwide Requirements
  docs/requirements/system-wide_requirements.adoc
Labels: documentation

#94 Dokusprint projectplan
  docs/project_management/project_plan.adoc
  docs/project_management/responsibilities.adoc
Labels: documentation

#97 Refined Use cases
  docs/requirements/images/uc01_wireframe.png
  docs/requirements/use_case_01.inc.adoc
  docs/requirements/use_case_03.inc.adoc
  docs/resources/Skizze von Wireframe Use Case Modell 01.vpp
  docs/resources/UC03 Wireframe.vpp
  docs/resources/uc01_wireframe.vpp
Labels: documentation

#100 Dokusprint iteration plans
  docs/project_management/iteration_plan_02.adoc
  docs/project_management/iteration_plan_03.adoc
  docs/project_management/iteration_plan_04.adoc
Labels: documentation

#99 Projektabgabe - first version of final "Abgabetemplate"
  belegabgabe_se1/se1_belegabgabe_t00.adoc
  docs/project_management/responsibilities.adoc
Labels: documentation

#103 Finalisierung Glossar
  belegabgabe_se1/se1_belegabgabe_i05.adoc
  docs/requirements/glossary.adoc
Labels: documentation

#104 Finalized various documents
  docs/architecture/architecture_notebook.adoc
  docs/project_management/project_plan.adoc
  docs/project_management/resources/Risklist.csv
  docs/project_management/risk_list.adoc
  docs/requirements/domain_model.adoc
  docs/requirements/system-wide_requirements.adoc
  docs/requirements/vision.adoc
Labels: documentation

#105 Finalized various documents
  docs/.gitignore
  docs/project_management/images/alphas_it02.png
  docs/project_management/images/alphas_it03.png
  docs/project_management/iteration_plan_02.adoc
  docs/project_management/iteration_plan_03.adoc
  docs/requirements/images/Wireframe UC03 - Initial.png
  docs/requirements/images/uc01_wireframe.png
  docs/resources/Skizze von Wireframe Use Case Modell 01.vpp
  docs/resources/UC03 Wireframe.vpp
  docs/resources/uc01_wireframe.vpp
Labels: documentation

#106 FORMATTING: added forced page breaks and image captions
  docs/architecture/architecture_notebook.adoc
  docs/project_management/iteration_plan_02.adoc
  docs/project_management/iteration_plan_03.adoc
  docs/project_management/project_plan.adoc
  docs/project_management/risk_list.adoc
  docs/requirements/domain_model.adoc
  docs/requirements/glossary.adoc
  docs/requirements/use-case_model.adoc
  docs/requirements/vision.adoc
  docs/test/test_cases.adoc
Labels: documentation

#107 more page breaks and table/column sizing corrections
  docs/project_management/iteration_plan_02.adoc
  docs/project_management/iteration_plan_03.adoc
  docs/project_management/project_plan.adoc
  docs/project_management/risk_list.adoc
  docs/requirements/glossary.adoc
  docs/requirements/use_case_01.inc.adoc
  docs/requirements/use_case_03.inc.adoc
  docs/requirements/vision.adoc
Labels: documentation
